app/models.py
from cassandra.cluster import Cluster
from flask import jsonify

cluster = Cluster(['localhost'])
session = cluster.connect()
session.set_keyspace('task_manager')


def listar_tarefas():
    tasks = session.execute('SELECT * FROM Task')
    return tasks


def adicionar_tarefa(task_description):
    descricao = task_description
    if descricao:
        session.execute('INSERT INTO Task (id, description) VALUES (uuid(), %s)', [task_description])
        return jsonify({'message': 'Tarefa adicionada com sucesso!'})
    else:
        return jsonify({'error': 'A descrição da tarefa é obrigatória.'}), 400


def remover_tarefa(task_id):
    session.execute('DELETE FROM Task WHERE id = %s', [task_id])
    return jsonify({'message': 'Tarefa removida com sucesso!'})

app/__init__.py
from flask import Flask
from config import CassandraConfig
from app.routes import task_routes

app = Flask(__name__)
app.config.from_object(CassandraConfig)

app.register_blueprint(task_routes)

app/routes.py
from uuid import UUID

from flask import Blueprint, render_template, request, redirect, url_for
import app.models as tarefa_model

task_routes = Blueprint('task_routes', __name__)


@task_routes.route('/')
def index():
    task = tarefa_model.listar_tarefas()
    return render_template('index.html', tasks=task)


@task_routes.route('/add_Task', methods=['POST'])
def add_task():
    task_description = request.form['task_description']
    tarefa_model.adicionar_tarefa(task_description)
    return redirect(url_for('task_routes.index'))


@task_routes.route('/delete_task/<task_id>')
def delete_task(task_id):
    task_id = UUID(task_id)
    tarefa_model.remover_tarefa(task_id)
    return redirect(url_for('task_routes.index'))

app/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Gerenciador de Tarefas</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>

<a class="row_flex" href="https://cassandra.apache.org/_/index.html">
    <img src="{{ url_for('static', filename='images/CassandraDB_Logo.png') }}">
</a>

<h1>Gerenciador de Tarefas</h1>
<form method="post" action="{{ url_for('task_routes.add_task') }}">
    <input class="InputSearch" type="text" name="task_description" placeholder="Descrição da Tarefa" required>
    <button class="ButtonPrimary" type="submit">Adicionar</button>
</form>

<h2>Tarefas:</h2>
<table border="1">
    <thead>
    <tr>
        <th>ID</th>
        <th>Descrição</th>
        <th>Ação</th>
    </tr>
    </thead>
    <tbody>
    {% for task in tasks %}
    <tr>
        <td>{{ task["id"] }}</td>
        <td>{{ task["description"] }}</td>
        <td><a href="{{ url_for('task_routes.delete_task', task_id=task.id) }}">Remover</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>


<ul>
    {% for task in tasks %}
    <li>{{ task.description }}
        <form method="post" action="{{ url_for('task_routes.delete_task', task_id=task.id) }}">
            <button type="submit">Excluir</button>
        </form>
    </li>
    {% endfor %}
</ul>


</body>
</html>